spring.application.name=project
app.name=Smart Product Management System
app.version=1.0
imageSize=5242880
spring.datasource.url=jdbc:mysql://localhost:3306/productdb
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.security.user.password=${SECURITY_PASSWORD}
jwt.secret=my-super-secret-key-my-super-secret-key